Listen /home/wineuser/.cups/cups.sock
User wineuser
Group wineuser
MaxRequestSize 0
DefaultEncryption Never
LogLevel info
FatalErrors none

<Location />
  Order allow,deny
  Allow all
</Location>

<Policy default>
  <Limit All>
    Order allow,deny
    Allow all
  </Limit>
</Policy>
